### PR TITLE
(TK-182) Illegal argument exception on 204 response

### PR DESCRIPTION
**Pull request by jpinsonault**

### CODE REVIEW

**Comment by dankreek** [comment]
This looks good, but it looks like the commit message should be something more about properly handling an empty body in a response. An HTTP 204 error code doesn't seem to be involved here.

**Comment by fpringvaldsen** [comment]
I also think we should update the commit message. Otherwise I'm :+1:

**Comment by jpinsonault** [comment]
@dankreek @fpringvaldsen Good call, I updated the commit message

**Comment by jpinsonault** [comment]
@dankreek @fpringvaldsen I've changed the function to change the nil body into an empty string in response to the jira conversation

**Comment by fpringvaldsen** [comment]
I think we should fix the trailing commit message for commit  dcad73d, and also add either `(TK-182)` or `(MAINT)` to the message for f9ad4a3, and then I'm good with merging this

**Comment by camlow325** [comment]
@jpinsonault - The original ticket noted that the problem can also be seen when a request is made down through the JavaClient API - not just the Clojure-level one.  Can you include a fix for the JavaClient side of this on the PR as well?

**Comment by jpinsonault** [comment]
@fpringvaldsen Reworded the commit message

@camlow325 Thanks for pointing that out, added the same fix and test for the java client as well

**Comment by fpringvaldsen** [comment]
:+1:

**Comment by camlow325** [comment]
:+1:

**Pull request merged**
